name: Dependency Review
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    uses: techops/reusable-workflows/.github/workflows/dependency-review.yaml@main
    secrets: inherit
